create table if not exists toeic_users (
  user_id text primary key,
  display_name text not null,
  salt text not null,
  pin_hash text not null,
  created_at text not null
);

create table if not exists toeic_history (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  "user" text not null,
  word text not null,
  direction text not null,
  user_answer text not null,
  result text not null,
  mode text not null,
  reason text not null,
  next_review text not null
);

create index if not exists toeic_history_user_idx on toeic_history ("user");
create index if not exists toeic_history_word_idx on toeic_history (word);

grant usage on schema public to service_role;
grant select, insert, update, delete on public.toeic_users to service_role;
grant select, insert, update, delete on public.toeic_history to service_role;
grant usage, select on sequence public.toeic_history_id_seq to service_role;
